apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata: # Dictionary
      name: myapp
      labels: # Dictionary
        app: myapp
    spec:
      containers: # List
        - name: myapp
          image: jainankur2/loylogic:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
